server:
  port: 8002
mysql:
  # host: 127.0.0.1
  host: localhost
  port: 3306
  username: root
  password: lqad1699
  database: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
log:
  log_level: debug
  log_file_name: ./storages/logs/shopdevgo.log
  max_size: 500
  max_age: 28
  compress: true